### ISSUE TITLE
Unable to build libresource

### ISSUE THREAD

**Issue by anjalidk** [lxc/libresource#14]
Hi,
I am unable to build libresource, with this error: "error: required file './ltmain.sh' not found". See below:
-bash-4.2$ automake --add-missing
configure.ac:22: installing './config.guess'
configure.ac:22: installing './config.sub'
configure.ac:23: installing './install-sh'
configure.ac:22: error: required file './ltmain.sh' not found
configure.ac:23: installing './missing'
Makefile.am: installing './depcomp'

Can anyone please help?

**Comment by anjalidk** [comment]
@rahuyada  @hallyn can you please comment? I am unable to build this.

**Comment by anjalidk** [comment]
These are the steps I followed to build this:
-bash-4.2$ aclocal
-bash-4.2$ autoconf
-bash-4.2$ automake --add-missing

**Comment by hallyn** [comment]
I don't know.  @rahuyada ?

**Comment by anjalidk** [comment]
I could build it by running libtoolize first.
But. how to include this library in my test program? I dont see any .so or .a library file..
@hallyn have you used this? @rahuyada ?
Anjali

**Comment by anjalidk** [comment]
Hi ,
Can someone please give me commit/push access to
https://github.com/lxc/libresource.git


Thanks
Anjali
________________________________

**Comment by hallyn** [comment]
> Hi , Can someone please give me commit/push access to https://github.com/lxc/libresource.git Thanks Anjali

that's not how this works.  Simply 'fork' the repo into your own account, commit your changes in a branch, and open a pull request.

**Comment by anjalidk** [comment]
Thanks Serge. I am taking over this project and will be the primary contributer to this project - in that case - I thought I should have push permissions directly to this repo?
Thanks
Anjali
________________________________

**Comment by hallyn** [comment]
@anjalidk  is there a public forum where this has been discussed, or is this a private handover?

If you are interested in this project that is great, but if it stays under the lxc organization, then I would like to first see some good PRs from you, then after we've gotten to know each other we can discuss repo permissions.

**Comment by anjalidk** [comment]
Hi Serge,
I created a pull request for removing the libtool infra
https://github.com/lxc/libresource/pull/15

Thanks
Anjali

________________________________

**Comment by anjalidk** [comment]
Hi ,

Can you please give me commit/push access to
https://github.com/lxc/libresource.git


Thanks
Anjali

________________________________
