### ISSUE TITLE
cgroup aware meminfo and other resources

### ISSUE THREAD

**Issue by rahuyada** [lxc/libresource#4]
I am planning to make meminfo in libresrouce cgroup aware. I am thinking to use following methodology.

1: look at /proc/self/cgroup and check cgroup name for memory sysystem.
2: look at /proc/self/mountinfo and check where cgroup fs is mounted at.
3: read info from mountpoint for memory/cgroup name/memory.
 
Does that sound a right way to do it? Are there any more suggestions ?

**Comment by brauner** [comment]
On Tue, Apr 02, 2019 at 12:41:42PM -0700, Rahul Yadav wrote:
> I am planning to make meminfo in libresrouce cgroup aware. I am thinking to use following methodology.
> 
> 1: look at /proc/self/cgroup and check cgroup name for memory sysystem.
> 2: look at /proc/self/mountinfo and check where cgroup fs is mounted at.
> 3: read info from mountpoint for memory/cgroup name/memory.
>  
> Does that sound a right way to do it? Are there any more suggestions ?

Yes, that looks correct and is basically what we do too. The only
difference is that we assume that cgroups are mounted at /sys/fs/cgroup
so we don't do costly parsing of all of mountinfo.

Thanks!
Christian

**Comment by rahuyada** [comment]
I too probably will go with that assumption, as all users of library we have now care  about performance and the assumption saves time and computation both.
If we have a use case to change this assumption in future, we can do that later.
Will send the code for review soon.
